server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000
  session:
    timeout: 6000

spring:
  profiles:
    # 这个属性就是区分具体加载的什么环境的配置文件，如application-prod.yml
    active: dev
  application:
    name: AlanApp